export const airlines: Record<string, string> = {
  AAL: "American Airlines",
  AIC: "Air India",
  ANA: "All Nippon Airways",
  ANZ: "Air New Zealand",
  ASA: "Alaska Airlines",
  ASL: "Air Serbia",
  BAW: "British Airways",
  CPA: "Cathay Pacific",
  DAL: "Delta Air Lines",
  EVA: "EVA Air",
  FJI: "Fiji Airways",
  HAL: "Hawaiian Airlines",
  JST: "Jetstar",
  JSX: "JSX",
  QFA: "Qantas",
  SJX: "Starlux Airlines",
  SWA: "Southwest Airlines",
  UAL: "United Airlines",
  VIR: "Virgin Atlantic",
  VJC: "VietJet Air",
  VOZ: "Virgin Australia",
};
