/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TravelIndexRouteImport } from './routes/travel/index'
import { Route as GolfRIndexRouteImport } from './routes/golf-r/index'
import { Route as ExperienceIndexRouteImport } from './routes/experience/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as BnbIndexRouteImport } from './routes/bnb/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as BlogSlugIndexRouteImport } from './routes/blog/$slug/index'
import { Route as AdminTravelIndexRouteImport } from './routes/admin/travel/index'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin/projects/index'
import { Route as AdminGolfRIndexRouteImport } from './routes/admin/golf-r/index'
import { Route as AdminExperiencesIndexRouteImport } from './routes/admin/experiences/index'
import { Route as AdminEducationIndexRouteImport } from './routes/admin/education/index'
import { Route as AdminCompaniesIndexRouteImport } from './routes/admin/companies/index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin/blog/index'
import { Route as AdminBlogCategoriesIndexRouteImport } from './routes/admin/blog/categories/index'
import { Route as AdminBlogIdIndexRouteImport } from './routes/admin/blog/$id/index'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelIndexRoute = TravelIndexRouteImport.update({
  id: '/travel/',
  path: '/travel/',
  getParentRoute: () => rootRouteImport,
} as any)
const GolfRIndexRoute = GolfRIndexRouteImport.update({
  id: '/golf-r/',
  path: '/golf-r/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceIndexRoute = ExperienceIndexRouteImport.update({
  id: '/experience/',
  path: '/experience/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const BnbIndexRoute = BnbIndexRouteImport.update({
  id: '/bnb/',
  path: '/bnb/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const BlogSlugIndexRoute = BlogSlugIndexRouteImport.update({
  id: '/blog/$slug/',
  path: '/blog/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTravelIndexRoute = AdminTravelIndexRouteImport.update({
  id: '/travel/',
  path: '/travel/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGolfRIndexRoute = AdminGolfRIndexRouteImport.update({
  id: '/golf-r/',
  path: '/golf-r/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExperiencesIndexRoute = AdminExperiencesIndexRouteImport.update({
  id: '/experiences/',
  path: '/experiences/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEducationIndexRoute = AdminEducationIndexRouteImport.update({
  id: '/education/',
  path: '/education/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompaniesIndexRoute = AdminCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogCategoriesIndexRoute =
  AdminBlogCategoriesIndexRouteImport.update({
    id: '/blog/categories/',
    path: '/blog/categories/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminBlogIdIndexRoute = AdminBlogIdIndexRouteImport.update({
  id: '/blog/$id/',
  path: '/blog/$id/',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/bnb/': typeof BnbIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/experience/': typeof ExperienceIndexRoute
  '/golf-r/': typeof GolfRIndexRoute
  '/travel/': typeof TravelIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/companies/': typeof AdminCompaniesIndexRoute
  '/admin/education/': typeof AdminEducationIndexRoute
  '/admin/experiences/': typeof AdminExperiencesIndexRoute
  '/admin/golf-r/': typeof AdminGolfRIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/travel/': typeof AdminTravelIndexRoute
  '/blog/$slug/': typeof BlogSlugIndexRoute
  '/admin/blog/$id/': typeof AdminBlogIdIndexRoute
  '/admin/blog/categories/': typeof AdminBlogCategoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/bnb': typeof BnbIndexRoute
  '/contact': typeof ContactIndexRoute
  '/experience': typeof ExperienceIndexRoute
  '/golf-r': typeof GolfRIndexRoute
  '/travel': typeof TravelIndexRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/companies': typeof AdminCompaniesIndexRoute
  '/admin/education': typeof AdminEducationIndexRoute
  '/admin/experiences': typeof AdminExperiencesIndexRoute
  '/admin/golf-r': typeof AdminGolfRIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/admin/travel': typeof AdminTravelIndexRoute
  '/blog/$slug': typeof BlogSlugIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdIndexRoute
  '/admin/blog/categories': typeof AdminBlogCategoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/bnb/': typeof BnbIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/experience/': typeof ExperienceIndexRoute
  '/golf-r/': typeof GolfRIndexRoute
  '/travel/': typeof TravelIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/companies/': typeof AdminCompaniesIndexRoute
  '/admin/education/': typeof AdminEducationIndexRoute
  '/admin/experiences/': typeof AdminExperiencesIndexRoute
  '/admin/golf-r/': typeof AdminGolfRIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/travel/': typeof AdminTravelIndexRoute
  '/blog/$slug/': typeof BlogSlugIndexRoute
  '/admin/blog/$id/': typeof AdminBlogIdIndexRoute
  '/admin/blog/categories/': typeof AdminBlogCategoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/'
    | '/blog/'
    | '/bnb/'
    | '/contact/'
    | '/experience/'
    | '/golf-r/'
    | '/travel/'
    | '/admin/blog/'
    | '/admin/companies/'
    | '/admin/education/'
    | '/admin/experiences/'
    | '/admin/golf-r/'
    | '/admin/projects/'
    | '/admin/travel/'
    | '/blog/$slug/'
    | '/admin/blog/$id/'
    | '/admin/blog/categories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/blog'
    | '/bnb'
    | '/contact'
    | '/experience'
    | '/golf-r'
    | '/travel'
    | '/admin/blog'
    | '/admin/companies'
    | '/admin/education'
    | '/admin/experiences'
    | '/admin/golf-r'
    | '/admin/projects'
    | '/admin/travel'
    | '/blog/$slug'
    | '/admin/blog/$id'
    | '/admin/blog/categories'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/'
    | '/blog/'
    | '/bnb/'
    | '/contact/'
    | '/experience/'
    | '/golf-r/'
    | '/travel/'
    | '/admin/blog/'
    | '/admin/companies/'
    | '/admin/education/'
    | '/admin/experiences/'
    | '/admin/golf-r/'
    | '/admin/projects/'
    | '/admin/travel/'
    | '/blog/$slug/'
    | '/admin/blog/$id/'
    | '/admin/blog/categories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogIndexRoute: typeof BlogIndexRoute
  BnbIndexRoute: typeof BnbIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  ExperienceIndexRoute: typeof ExperienceIndexRoute
  GolfRIndexRoute: typeof GolfRIndexRoute
  TravelIndexRoute: typeof TravelIndexRoute
  BlogSlugIndexRoute: typeof BlogSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel/': {
      id: '/travel/'
      path: '/travel'
      fullPath: '/travel/'
      preLoaderRoute: typeof TravelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/golf-r/': {
      id: '/golf-r/'
      path: '/golf-r'
      fullPath: '/golf-r/'
      preLoaderRoute: typeof GolfRIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/': {
      id: '/experience/'
      path: '/experience'
      fullPath: '/experience/'
      preLoaderRoute: typeof ExperienceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bnb/': {
      id: '/bnb/'
      path: '/bnb'
      fullPath: '/bnb/'
      preLoaderRoute: typeof BnbIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/$slug/': {
      id: '/blog/$slug/'
      path: '/blog/$slug'
      fullPath: '/blog/$slug/'
      preLoaderRoute: typeof BlogSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/travel/': {
      id: '/admin/travel/'
      path: '/travel'
      fullPath: '/admin/travel/'
      preLoaderRoute: typeof AdminTravelIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/golf-r/': {
      id: '/admin/golf-r/'
      path: '/golf-r'
      fullPath: '/admin/golf-r/'
      preLoaderRoute: typeof AdminGolfRIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/experiences/': {
      id: '/admin/experiences/'
      path: '/experiences'
      fullPath: '/admin/experiences/'
      preLoaderRoute: typeof AdminExperiencesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/education/': {
      id: '/admin/education/'
      path: '/education'
      fullPath: '/admin/education/'
      preLoaderRoute: typeof AdminEducationIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/companies/': {
      id: '/admin/companies/'
      path: '/companies'
      fullPath: '/admin/companies/'
      preLoaderRoute: typeof AdminCompaniesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/categories/': {
      id: '/admin/blog/categories/'
      path: '/blog/categories'
      fullPath: '/admin/blog/categories/'
      preLoaderRoute: typeof AdminBlogCategoriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/$id/': {
      id: '/admin/blog/$id/'
      path: '/blog/$id'
      fullPath: '/admin/blog/$id/'
      preLoaderRoute: typeof AdminBlogIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminCompaniesIndexRoute: typeof AdminCompaniesIndexRoute
  AdminEducationIndexRoute: typeof AdminEducationIndexRoute
  AdminExperiencesIndexRoute: typeof AdminExperiencesIndexRoute
  AdminGolfRIndexRoute: typeof AdminGolfRIndexRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
  AdminTravelIndexRoute: typeof AdminTravelIndexRoute
  AdminBlogIdIndexRoute: typeof AdminBlogIdIndexRoute
  AdminBlogCategoriesIndexRoute: typeof AdminBlogCategoriesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminCompaniesIndexRoute: AdminCompaniesIndexRoute,
  AdminEducationIndexRoute: AdminEducationIndexRoute,
  AdminExperiencesIndexRoute: AdminExperiencesIndexRoute,
  AdminGolfRIndexRoute: AdminGolfRIndexRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
  AdminTravelIndexRoute: AdminTravelIndexRoute,
  AdminBlogIdIndexRoute: AdminBlogIdIndexRoute,
  AdminBlogCategoriesIndexRoute: AdminBlogCategoriesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogIndexRoute: BlogIndexRoute,
  BnbIndexRoute: BnbIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  ExperienceIndexRoute: ExperienceIndexRoute,
  GolfRIndexRoute: GolfRIndexRoute,
  TravelIndexRoute: TravelIndexRoute,
  BlogSlugIndexRoute: BlogSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
